### ISSUE TITLE
Rename "success" to "ok"

### ISSUE THREAD

**Issue by andreogle** [api3dao/promise-utils#54]
@Siegrift what do you think about renaming `success` to `ok`? "ok" is shorter, so takes up less space on a given line, and it's (arguably) a bit more common as a keyword than "success". Obviously this would be a breaking change though and would require a major version bump.

Edit: sorry shouldn't have tagged the core team

**Comment by Siegrift** [comment]
> and it's (arguably) a bit more common as a keyword than "success"

Arguably :D. zod also uses the nomenclature we have https://github.com/colinhacks/zod#safeparse.

This change does feel necessary to me and we would need to upgrade other repos (at least at some point).

**Comment by Siegrift** [comment]
Btw. you could create a tiny wrapper around promise utils that does this only for chainAPI.

**Comment by andreogle** [comment]
> This change does feel necessary to me

"Does feel necessary" - do you mean that you agree with this suggestion?

> a tiny wrapper around promise utils

Also very true 👍🏻

**Comment by Siegrift** [comment]
> "Does feel necessary" - do you mean that you agree with this suggestion?

Sorry, I am missing NOT there (does not feel necessary).

**Comment by andreogle** [comment]
Fair enough. Let's keep it as is then
