### ISSUE TITLE
Promise utils should handle negative timeouts

### ISSUE THREAD

**Issue by Siegrift** [api3dao/promise-utils#56]
Initially found in https://github.com/api3dao/airnode/pull/1352/commits/1fb137690477a03dbcaaa2f54ac857f9e1c418ec#diff-031f6e4c71f446e78eeb4607ed8773e20ba6886b9d4029fdaaba675b0cd75c89R578

Reasonable options seem to me:
* throw wen negative timeout is passed (maybe clearer conceptually, but users need to check for this on their own)
* accept negative timeout and reject immediately (easier to use)

**Comment by amarthadan** [comment]
:thinking: I don't know. I guess I would prefer option a). Imagine you have some flow
```
const goResult = await go(() => doSomething(), goOptions)
if (!goResult.success) {
  log.warn(`Doing something went wrong: ${goResult.error}`)
}
```
How would you distinguish between an error in the `doSomething` function and the wrong options for the `go` function? If I'm in the `if` block I would expect that the error there is due to `doSomething` being unsuccessful.

Throwing an error due to a bad argument makes imo more sense.

**Comment by Siegrift** [comment]
Disadvantage of a) is that you expect `go` to never throw which is an invariant as of now and the whole point of using it.

**Comment by amarthadan** [comment]
I understand that. But it still feels weird mixing `go` processing errors and errors from the function running within.

**Comment by Siegrift** [comment]
@amarthadan @andreogle How do you feel about this? 

I'd rather go with option a), but the non-throwing version. go utils throwing is more severe than error handling, which is most often used to return early or log the error somewhere).

**Comment by andreogle** [comment]
I'm not 100% sure I'm following the context, but I kinda think it should work the same as `setTimeout` does and treat negative values as 0. I don't feel strongly about this though and I'm fine with either option

**Comment by amarthadan** [comment]
What do you mean by
> I'd rather go with option a), but the non-throwing version.

That's basically the second option.

**Comment by Siegrift** [comment]
I was [referring to your suggestion](https://github.com/api3dao/promise-utils/issues/56#issuecomment-1209003055).

What andre proposes is similar to option b), but instead of rejecting in resolves immediately. That makes sense as well. I quite like that.

**Comment by amarthadan** [comment]
> What andre proposes is similar to option b), but instead of rejecting in resolves immediately. That makes sense as well. I quite like that.

Yeah, that should work.

**Comment by Siegrift** [comment]
Ok, actually the promise number is then passed to the setTimeout so there is no change needed to achieve the behaviour we want... 

If this becomes an issue again, we may consider adding a warning log or something, but I'll close the issue as "working as expected" now.
