### ISSUE TITLE
Make promise utils result union uniform

### ISSUE THREAD

**Issue by Siegrift** [api3dao/promise-utils#67]
I've noticed that TS inference improved starting from version 4.6 which remembers relationships of the types even when they are destructured... This would allow us to make the results uniform and the following could work:

```
const { success, error, data } = goSync(() => 123);
// @ts-expect-error should not work
const x: number = data;
if (success) {
  const xx: number = data;
}
```

Currently, you are only able to access the `success` property before accessing the `data` or `error` properties. See the proposal in [TS playground](https://www.typescriptlang.org/play?jsx=0&ts=4.6.4#code/KYDwDg9gTgLgBDAnmYcDiEBKwDOBXAGxgGU8BjM3HAHgBUA+OAXjgG84ATAQxi4C44tANxxgUKNAF4Adh2AAzAJbTgHEfgpUBMKHlQBfIQChQkWAmSoM2fEQCi46NTuiQMYLJxwHEqM2+OUIws7Ny8UrIKyqoiYr4CdurklDg4AvJcBDgGxqbQ8Ego6Fi4hDB0ADTeru6eAb7+PtDBxTZlpJqpdIwAPq2l9oHO9MYm4PlwZBDSOPAaKTgAYtL+3QAUAG6ZegK0AJQC1gMkyVTdzIysRnBwUMAweFAr7PNaCLrAVWH8cFsEelU4pI4DI5EoVBw4IYjNC8uYpjN4BlFARlqsXKBahwvE0gms4glAgd+rYYLjhhc2NdbvdHs84K9UulMtlAYEBHE4FwcV8eD9QVEIVDjNCxmZ4GQCNyvBgAOpQLhgFAcXE1DzY+rQKk3BGzXRkGDQNZgPAAIwIijINO50wiAGtpBAAO7SPbam4MvAoKBrADkvrgAGprThpntjDd9DCjEZdRK7jxgBhVSxnGq6rj6PjxPbHS7iUdSeS7MFLtTFPI4Nm-MpZlxpJQIJXcW67g8nnBkajpNXw9S23TO1wUcs1ioncV5Yrlbje33RXCJdNZnAAOYQYiIBurWhVDFudU4wJZ+TSARrN1MRj7Q4lUmVbyl906RDum4DjuMpY908XvuRyYeDIAALKs4jdK4PRpdsVjIBN3GTQJey5GU7zKYsRmpKNRVjZd4BeU5UjZXxeV4KF-HXTcGzWC9KQARgAJgAZj7AB6Vi4AAARgHAAFpTGAA1+MCBlgIgQhIUdeAnWgO1cMROAQAEaQ8AAW1NMR-G+YwKyrL8IOpONFKUuAVPUzSWG0mEgA)

For reference, this is already how `useQuery` from `react-query` works.

**Comment by amarthadan** [comment]
Can you give an example of what is it good for? I quite like that you can't access other fields than `success` without checking its value. It kinda forces you to do the error handling which is what you usually want.

**Comment by amarthadan** [comment]
> Without checking the success the type of data: T | undefined. Only after you check the success property you'll get data: T

But that's the point. It's telling you to check it.

> And there is no reason for preventing access to these properties.

Again, it's kind of a point of it. It forces you to check and that check is most likely some kind of error handling.

**Comment by Siegrift** [comment]
> But that's the point. It's telling you to check it.

Yeah. It tell you to check the property for `undefined` before using it, but also allows you to access the property. E.g.
```js
const maybeLog = (e: Error | undefined) => {
  if (e) console.error(e)
}
const goRes = await go(...)
maybeLog(goRes.error)
```

vs

```
const maybeLog = (e: Error | undefined) => {
  if (e) console.error(e)
}
const goRes = await go(...)
if (goRes.error) maybeLog(goRes.error)
```
